name: rethinking
channels: 
    - defaults
    - conda-forge
    - anaconda
dependencies:
    - numpy=1.16.4
    - pandas=0.24.2
    - pip=19.1.1
    - pystan=2.19.1.1
    - python=3.7.4
    - scikit-learn=0.20.0
    - scipy=1.4.1
    - pip:
        - arviz==0.2.0
        - Cython==0.29.14
        - matplotlib==3.1.2
        - pymc3==3.8
        - seaborn==0.9.0
        - theano==1.0.2



